FROM trufflesuite/ganache-cli

# RUN apt-get update

# RUN apt-get install -y nodejs
# RUN apt-get install -y npm

RUN npm install -y -g truffle; exit 0;
# RUN npm install -y -g ganache-cli

RUN mkdir -p /balancer

WORKDIR /balancer

ADD https://github.com/balancer-labs/balancer-core/archive/master.tar.gz balancer-core.tar.gz

RUN tar -zxvf balancer-core.tar.gz

WORKDIR /balancer/balancer-core-master

RUN yarn compile; exit 0;
