export const bFactory = 'BFactory'
export const crpFactory = 'CRPFactory'
export const crp = 'ConfigurableRightsPool'
export const pool = 'BPool'
export const aToken = 'AToken'
export const bToken = 'BToken'
export const reserveToken = 'ReserveToken'
