/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { IERC20 } from "./IERC20";
export type { IPrestige } from "./IPrestige";
export type { Prestige } from "./Prestige";
export type { PrestigeByConstruction } from "./PrestigeByConstruction";
export type { MaliciousClaimPrestige } from "./MaliciousClaimPrestige";
export type { PrestigeByConstructionClaimTest } from "./PrestigeByConstructionClaimTest";
export type { PrestigeByConstructionTest } from "./PrestigeByConstructionTest";
export type { TVKPrestige } from "./TVKPrestige";

export { ERC20__factory } from "./factories/ERC20__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export { IPrestige__factory } from "./factories/IPrestige__factory";
export { Prestige__factory } from "./factories/Prestige__factory";
export { PrestigeByConstruction__factory } from "./factories/PrestigeByConstruction__factory";
export { MaliciousClaimPrestige__factory } from "./factories/MaliciousClaimPrestige__factory";
export { PrestigeByConstructionClaimTest__factory } from "./factories/PrestigeByConstructionClaimTest__factory";
export { PrestigeByConstructionTest__factory } from "./factories/PrestigeByConstructionTest__factory";
export { TVKPrestige__factory } from "./factories/TVKPrestige__factory";
