/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { IPrestige } from "./IPrestige";
export type { Prestige } from "./Prestige";
export type { PrestigeByConstruction } from "./PrestigeByConstruction";
export type { TVKPrestige } from "./TVKPrestige";

export { IERC20__factory } from "./factories/IERC20__factory";
export { IPrestige__factory } from "./factories/IPrestige__factory";
export { Prestige__factory } from "./factories/Prestige__factory";
export { PrestigeByConstruction__factory } from "./factories/PrestigeByConstruction__factory";
export { TVKPrestige__factory } from "./factories/TVKPrestige__factory";
