/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IPrestigeInterface extends ethers.utils.Interface {
  functions: {
    "index_current_report(address)": FunctionFragment;
    "set_status(address,uint8,bytes)": FunctionFragment;
    "status_report(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "index_current_report",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "set_status",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "status_report",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "index_current_report",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "set_status", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "status_report",
    data: BytesLike
  ): Result;

  events: {
    "StatusChange(address,uint8[2])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "StatusChange"): EventFragment;
}

export class IPrestige extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IPrestigeInterface;

  functions: {
    index_current_report(
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "index_current_report(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    set_status(
      account: string,
      new_status: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "set_status(address,uint8,bytes)"(
      account: string,
      new_status: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    status_report(
      account: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    "status_report(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<[number]>;
  };

  index_current_report(
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "index_current_report(address)"(
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  set_status(
    account: string,
    new_status: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "set_status(address,uint8,bytes)"(
    account: string,
    new_status: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  status_report(account: string, overrides?: CallOverrides): Promise<number>;

  "status_report(address)"(
    account: string,
    overrides?: CallOverrides
  ): Promise<number>;

  callStatic: {
    index_current_report(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "index_current_report(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    set_status(
      account: string,
      new_status: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "set_status(address,uint8,bytes)"(
      account: string,
      new_status: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    status_report(account: string, overrides?: CallOverrides): Promise<number>;

    "status_report(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<number>;
  };

  filters: {
    StatusChange(
      account: null,
      change: null
    ): TypedEventFilter<
      [string, [number, number]],
      { account: string; change: [number, number] }
    >;
  };

  estimateGas: {
    index_current_report(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "index_current_report(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    set_status(
      account: string,
      new_status: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "set_status(address,uint8,bytes)"(
      account: string,
      new_status: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    status_report(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "status_report(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    index_current_report(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "index_current_report(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    set_status(
      account: string,
      new_status: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "set_status(address,uint8,bytes)"(
      account: string,
      new_status: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    status_report(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "status_report(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
