/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface TVKPrestigeInterface extends ethers.utils.Interface {
  functions: {
    "bronze()": FunctionFragment;
    "chad()": FunctionFragment;
    "copper()": FunctionFragment;
    "diamond()": FunctionFragment;
    "gold()": FunctionFragment;
    "index_current_report(address)": FunctionFragment;
    "jawad()": FunctionFragment;
    "levels()": FunctionFragment;
    "platinum()": FunctionFragment;
    "set_status(address,uint8,bytes)": FunctionFragment;
    "silver()": FunctionFragment;
    "status_report(address)": FunctionFragment;
    "statuses(address)": FunctionFragment;
    "tvk()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "bronze", values?: undefined): string;
  encodeFunctionData(functionFragment: "chad", values?: undefined): string;
  encodeFunctionData(functionFragment: "copper", values?: undefined): string;
  encodeFunctionData(functionFragment: "diamond", values?: undefined): string;
  encodeFunctionData(functionFragment: "gold", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "index_current_report",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "jawad", values?: undefined): string;
  encodeFunctionData(functionFragment: "levels", values?: undefined): string;
  encodeFunctionData(functionFragment: "platinum", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "set_status",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "silver", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "status_report",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "statuses", values: [string]): string;
  encodeFunctionData(functionFragment: "tvk", values?: undefined): string;

  decodeFunctionResult(functionFragment: "bronze", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "chad", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "copper", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "diamond", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gold", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "index_current_report",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jawad", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "levels", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "platinum", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "set_status", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "silver", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "status_report",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "statuses", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tvk", data: BytesLike): Result;

  events: {
    "StatusChange(address,uint8[2])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "StatusChange"): EventFragment;
}

export class TVKPrestige extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TVKPrestigeInterface;

  functions: {
    bronze(overrides?: CallOverrides): Promise<[BigNumber]>;

    "bronze()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    chad(overrides?: CallOverrides): Promise<[BigNumber]>;

    "chad()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    copper(overrides?: CallOverrides): Promise<[BigNumber]>;

    "copper()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    diamond(overrides?: CallOverrides): Promise<[BigNumber]>;

    "diamond()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    gold(overrides?: CallOverrides): Promise<[BigNumber]>;

    "gold()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    index_current_report(
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "index_current_report(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    jawad(overrides?: CallOverrides): Promise<[BigNumber]>;

    "jawad()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    levels(
      overrides?: CallOverrides
    ): Promise<
      [
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ]
      ]
    >;

    "levels()"(
      overrides?: CallOverrides
    ): Promise<
      [
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ]
      ]
    >;

    platinum(overrides?: CallOverrides): Promise<[BigNumber]>;

    "platinum()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    set_status(
      account: string,
      new_status: BigNumberish,
      arg2: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "set_status(address,uint8,bytes)"(
      account: string,
      new_status: BigNumberish,
      arg2: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    silver(overrides?: CallOverrides): Promise<[BigNumber]>;

    "silver()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    status_report(
      account: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    "status_report(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    statuses(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "statuses(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tvk(overrides?: CallOverrides): Promise<[string]>;

    "tvk()"(overrides?: CallOverrides): Promise<[string]>;
  };

  bronze(overrides?: CallOverrides): Promise<BigNumber>;

  "bronze()"(overrides?: CallOverrides): Promise<BigNumber>;

  chad(overrides?: CallOverrides): Promise<BigNumber>;

  "chad()"(overrides?: CallOverrides): Promise<BigNumber>;

  copper(overrides?: CallOverrides): Promise<BigNumber>;

  "copper()"(overrides?: CallOverrides): Promise<BigNumber>;

  diamond(overrides?: CallOverrides): Promise<BigNumber>;

  "diamond()"(overrides?: CallOverrides): Promise<BigNumber>;

  gold(overrides?: CallOverrides): Promise<BigNumber>;

  "gold()"(overrides?: CallOverrides): Promise<BigNumber>;

  index_current_report(
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "index_current_report(address)"(
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  jawad(overrides?: CallOverrides): Promise<BigNumber>;

  "jawad()"(overrides?: CallOverrides): Promise<BigNumber>;

  levels(
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ]
  >;

  "levels()"(
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ]
  >;

  platinum(overrides?: CallOverrides): Promise<BigNumber>;

  "platinum()"(overrides?: CallOverrides): Promise<BigNumber>;

  set_status(
    account: string,
    new_status: BigNumberish,
    arg2: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "set_status(address,uint8,bytes)"(
    account: string,
    new_status: BigNumberish,
    arg2: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  silver(overrides?: CallOverrides): Promise<BigNumber>;

  "silver()"(overrides?: CallOverrides): Promise<BigNumber>;

  status_report(account: string, overrides?: CallOverrides): Promise<number>;

  "status_report(address)"(
    account: string,
    overrides?: CallOverrides
  ): Promise<number>;

  statuses(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "statuses(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tvk(overrides?: CallOverrides): Promise<string>;

  "tvk()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    bronze(overrides?: CallOverrides): Promise<BigNumber>;

    "bronze()"(overrides?: CallOverrides): Promise<BigNumber>;

    chad(overrides?: CallOverrides): Promise<BigNumber>;

    "chad()"(overrides?: CallOverrides): Promise<BigNumber>;

    copper(overrides?: CallOverrides): Promise<BigNumber>;

    "copper()"(overrides?: CallOverrides): Promise<BigNumber>;

    diamond(overrides?: CallOverrides): Promise<BigNumber>;

    "diamond()"(overrides?: CallOverrides): Promise<BigNumber>;

    gold(overrides?: CallOverrides): Promise<BigNumber>;

    "gold()"(overrides?: CallOverrides): Promise<BigNumber>;

    index_current_report(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "index_current_report(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    jawad(overrides?: CallOverrides): Promise<BigNumber>;

    "jawad()"(overrides?: CallOverrides): Promise<BigNumber>;

    levels(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ]
    >;

    "levels()"(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ]
    >;

    platinum(overrides?: CallOverrides): Promise<BigNumber>;

    "platinum()"(overrides?: CallOverrides): Promise<BigNumber>;

    set_status(
      account: string,
      new_status: BigNumberish,
      arg2: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "set_status(address,uint8,bytes)"(
      account: string,
      new_status: BigNumberish,
      arg2: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    silver(overrides?: CallOverrides): Promise<BigNumber>;

    "silver()"(overrides?: CallOverrides): Promise<BigNumber>;

    status_report(account: string, overrides?: CallOverrides): Promise<number>;

    "status_report(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<number>;

    statuses(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "statuses(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tvk(overrides?: CallOverrides): Promise<string>;

    "tvk()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    StatusChange(
      account: null,
      change: null
    ): TypedEventFilter<
      [string, [number, number]],
      { account: string; change: [number, number] }
    >;
  };

  estimateGas: {
    bronze(overrides?: CallOverrides): Promise<BigNumber>;

    "bronze()"(overrides?: CallOverrides): Promise<BigNumber>;

    chad(overrides?: CallOverrides): Promise<BigNumber>;

    "chad()"(overrides?: CallOverrides): Promise<BigNumber>;

    copper(overrides?: CallOverrides): Promise<BigNumber>;

    "copper()"(overrides?: CallOverrides): Promise<BigNumber>;

    diamond(overrides?: CallOverrides): Promise<BigNumber>;

    "diamond()"(overrides?: CallOverrides): Promise<BigNumber>;

    gold(overrides?: CallOverrides): Promise<BigNumber>;

    "gold()"(overrides?: CallOverrides): Promise<BigNumber>;

    index_current_report(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "index_current_report(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    jawad(overrides?: CallOverrides): Promise<BigNumber>;

    "jawad()"(overrides?: CallOverrides): Promise<BigNumber>;

    levels(overrides?: CallOverrides): Promise<BigNumber>;

    "levels()"(overrides?: CallOverrides): Promise<BigNumber>;

    platinum(overrides?: CallOverrides): Promise<BigNumber>;

    "platinum()"(overrides?: CallOverrides): Promise<BigNumber>;

    set_status(
      account: string,
      new_status: BigNumberish,
      arg2: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "set_status(address,uint8,bytes)"(
      account: string,
      new_status: BigNumberish,
      arg2: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    silver(overrides?: CallOverrides): Promise<BigNumber>;

    "silver()"(overrides?: CallOverrides): Promise<BigNumber>;

    status_report(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "status_report(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    statuses(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "statuses(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tvk(overrides?: CallOverrides): Promise<BigNumber>;

    "tvk()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    bronze(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "bronze()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    chad(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "chad()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    copper(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "copper()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    diamond(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "diamond()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gold(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "gold()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    index_current_report(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "index_current_report(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    jawad(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "jawad()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    levels(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "levels()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    platinum(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "platinum()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    set_status(
      account: string,
      new_status: BigNumberish,
      arg2: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "set_status(address,uint8,bytes)"(
      account: string,
      new_status: BigNumberish,
      arg2: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    silver(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "silver()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    status_report(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "status_report(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    statuses(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "statuses(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tvk(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tvk()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
